schema_version = "1.0.0"

id = "exploded_assembly_studio"
version = "1.13.0"
name = "Exploded Assembly Studio"
tagline = "Explode and assemble animations for mechanical and electronic assemblies"
maintainer = "Exploded Assembly Studio"
type = "add-on"

tags = ["Animation", "Object", "Render"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
