"""Property definitions for Exploded Assembly Studio.

Scene level settings live on ``Scene.eas`` and per object data on ``Object.eas``.
Nothing here touches mesh, material or origin data (see spec section 19).
"""

import bpy
from bpy.props import (
    BoolProperty,
    EnumProperty,
    FloatProperty,
    FloatVectorProperty,
    IntProperty,
    PointerProperty,
    StringProperty,
)
from bpy.types import Object, PropertyGroup, Scene

IDENTITY_16 = (
    1.0, 0.0, 0.0, 0.0,
    0.0, 1.0, 0.0, 0.0,
    0.0, 0.0, 1.0, 0.0,
    0.0, 0.0, 0.0, 1.0,
)

SOURCE_ITEMS = [
    ('SELECTED', "Selected Objects", "Use the objects currently selected in the viewport", 'RESTRICT_SELECT_OFF', 0),
    ('COLLECTION', "Collection", "Use every object inside the chosen collection", 'OUTLINER_COLLECTION', 1),
]

DIRECTION_ITEMS = [
    ('CENTER', "From Center", "Every part moves away from the assembly center (radial)", 'FULLSCREEN_ENTER', 0),
    ('AXIS_SPLIT', "Axis +/- (Split)", "Parts above the center move along +Axis, parts below along -Axis. "
                                       "Best for stacked products: PCB stays, components go up, bottom shell goes down", 'ARROW_LEFTRIGHT', 1),
    ('WORLD_AXIS', "World Axis", "Every part moves along the same world axis", 'EMPTY_ARROWS', 2),
    ('LOCAL_AXIS', "Local Axis", "Every part moves along its own local axis", 'ORIENTATION_LOCAL', 3),
]

AXIS_ITEMS = [
    ('X', "X", "World X axis"),
    ('Y', "Y", "World Y axis"),
    ('Z', "Z", "World Z axis"),
]

MAGNITUDE_ITEMS = [
    ('UNIFORM', "Uniform", "Every part travels the same distance"),
    ('PROPORTIONAL', "Proportional", "Parts further from the center travel further"),
    ('LAYERED', "Layered", "Distance multiplied by the part's layer index, so stacked parts fan out evenly"),
]

CENTER_ITEMS = [
    ('BOUNDS', "Bounding Box", "Center of the combined bounding box of all parts"),
    ('MEDIAN', "Median Point", "Average of the part origins"),
    ('CURSOR', "3D Cursor", "Use the 3D cursor position"),
    ('ACTIVE', "Active Object", "Use the active object's center"),
]

ORDER_ITEMS = [
    ('DISTANCE', "Distance From Center", "Outermost parts move first"),
    ('AXIS', "Axis Position", "Sorted by position along the explode axis"),
    ('NAME', "Name", "Alphabetical order"),
    ('COLLECTION', "Collection Order", "Order the objects appear in the collection / selection"),
    ('MANUAL', "Manual", "Use the per object Sequence Order value"),
]

INTERPOLATION_ITEMS = [
    ('BEZIER', "Bezier", "Smooth default easing"),
    ('LINEAR', "Linear", "Constant speed"),
    ('SINE', "Sine", "Gentle sinusoidal easing"),
    ('QUAD', "Quadratic", "Quadratic easing"),
    ('CUBIC', "Cubic", "Cubic easing"),
    ('EXPO', "Exponential", "Strong easing"),
    ('BACK', "Back", "Overshoots slightly, good for product ads"),
    ('ELASTIC', "Elastic", "Springy settle"),
]

EASING_ITEMS = [
    ('AUTO', "Automatic", "Let Blender choose"),
    ('EASE_IN', "Ease In", "Slow start"),
    ('EASE_OUT', "Ease Out", "Slow end"),
    ('EASE_IN_OUT', "Ease In Out", "Slow start and end"),
]


def _subject_poll(self, obj):
    """Only offer objects that can actually be framed."""
    if obj.eas.is_rig:
        return False
    return obj.type not in {'CAMERA', 'LIGHT', 'SPEAKER', 'LIGHT_PROBE'}


class EAS_ObjectProperties(PropertyGroup):
    """Per object assembly data. Stored in the .blend so it survives reloads."""

    has_state: BoolProperty(
        name="Has Assembly State",
        description="True when this object's assembled transform has been recorded",
        default=False,
    )
    assembly_matrix: FloatVectorProperty(
        name="Assembly Matrix",
        description="Recorded local (basis) matrix of the assembled state, row major",
        size=16,
        default=IDENTITY_16,
    )
    distance_multiplier: FloatProperty(
        name="Distance Multiplier",
        description="Scales this part's explode distance",
        default=1.0,
        soft_min=0.0,
        soft_max=5.0,
    )
    order: IntProperty(
        name="Sequence Order",
        description="Position in the staggered animation when Order Mode is Manual. Lower moves first",
        default=0,
        min=0,
    )
    exclude: BoolProperty(
        name="Exclude From Explosion",
        description="Keep this object pinned in place (it still gets an assembly state)",
        default=False,
    )
    is_rig: BoolProperty(
        name="Is Camera Rig",
        description="Marks objects generated by the add-on camera rig",
        default=False,
    )


class EAS_SceneProperties(PropertyGroup):
    """All add-on settings for one scene."""

    # ------------------------------------------------------------------ source
    source: EnumProperty(
        name="Source",
        description="Where the parts come from",
        items=SOURCE_ITEMS,
        default='SELECTED',
    )
    collection: PointerProperty(
        name="Collection",
        description="Collection holding the assembly",
        type=bpy.types.Collection,
    )
    visible_only: BoolProperty(
        name="Visible Only",
        description="Skip objects hidden in the current view layer",
        default=True,
    )
    skip_child_parts: BoolProperty(
        name="Skip Parented Children",
        description="If a part's parent is also part of the assembly, only the parent is animated so the "
                    "child follows it instead of moving twice",
        default=True,
    )

    # --------------------------------------------------------------- explosion
    direction: EnumProperty(
        name="Direction",
        description="How the explode vector is built for each part",
        items=DIRECTION_ITEMS,
        default='CENTER',
    )
    axis: EnumProperty(
        name="Axis",
        description="Axis used by the axis based direction modes",
        items=AXIS_ITEMS,
        default='Z',
    )
    distance: FloatProperty(
        name="Distance",
        description="Explode distance in scene units",
        default=2.0,
        soft_min=0.0,
        soft_max=50.0,
        unit='LENGTH',
    )
    magnitude: EnumProperty(
        name="Spacing",
        description="How the distance is distributed over the parts",
        items=MAGNITUDE_ITEMS,
        default='UNIFORM',
    )
    center_mode: EnumProperty(
        name="Center",
        description="Reference point of the assembly",
        items=CENTER_ITEMS,
        default='BOUNDS',
    )
    use_bounds_center: BoolProperty(
        name="Use Geometry Center",
        description="Measure each part from its bounding box center instead of its origin. Turn off for "
                    "CAD models whose origins carry meaning",
        default=True,
    )
    layer_tolerance: FloatProperty(
        name="Layer Tolerance",
        description="Fraction of the assembly size within which parts count as the same layer. Parts on the "
                    "same layer travel the same distance, and in Axis +/- mode parts inside this band around "
                    "the center stay put - that is what keeps the PCB still while everything else separates",
        default=0.02,
        min=0.0,
        max=1.0,
        subtype='FACTOR',
    )

    # ---------------------------------------------------------------- rotation
    use_rotation: BoolProperty(
        name="Rotate While Exploding",
        description="Add a spin to each part as it travels",
        default=False,
    )
    rotation_angle: FloatProperty(
        name="Rotation",
        description="Extra rotation applied at the exploded state",
        default=0.0,
        subtype='ANGLE',
        soft_min=-6.28319,
        soft_max=6.28319,
    )
    rotation_axis: EnumProperty(
        name="Rotation Axis",
        description="Axis the extra rotation spins around",
        items=AXIS_ITEMS,
        default='Z',
    )
    rotation_local: BoolProperty(
        name="Local Spin Axis",
        description="Spin around the part's own axis instead of the world axis",
        default=False,
    )

    # --------------------------------------------------------------- sequence
    use_sequence: BoolProperty(
        name="Staggered Sequence",
        description="Parts move one after another instead of all together",
        default=False,
    )
    order_mode: EnumProperty(
        name="Order",
        description="How the move order is decided",
        items=ORDER_ITEMS,
        default='DISTANCE',
    )
    reverse_order: BoolProperty(
        name="Reverse Order",
        description="Flip the computed order",
        default=False,
    )
    reverse_on_assemble: BoolProperty(
        name="Mirror Order On Assemble",
        description="Assemble plays the sequence backwards, so parts come back in the opposite order they left",
        default=True,
    )
    overlap: FloatProperty(
        name="Overlap",
        description="0 = strictly one part after another, 1 = all parts at the same time",
        default=0.6,
        min=0.0,
        max=1.0,
        subtype='FACTOR',
    )

    # -------------------------------------------------------------- animation
    frame_start: IntProperty(
        name="Start Frame",
        description="First frame of the generated animation",
        default=1,
    )
    frame_end: IntProperty(
        name="End Frame",
        description="Last frame of the generated animation",
        default=60,
    )
    interpolation: EnumProperty(
        name="Interpolation",
        description="F-Curve interpolation of the generated keyframes",
        items=INTERPOLATION_ITEMS,
        default='BEZIER',
    )
    easing: EnumProperty(
        name="Easing",
        description="Easing direction, ignored by Bezier and Linear",
        items=EASING_ITEMS,
        default='EASE_IN_OUT',
    )
    replace_animation: BoolProperty(
        name="Replace Existing",
        description="Remove existing transform keyframes on the parts before writing new ones",
        default=True,
    )
    set_scene_range: BoolProperty(
        name="Set Scene Frame Range",
        description="Also set the scene start/end frame to match",
        default=True,
    )
    auto_store_state: BoolProperty(
        name="Auto Save Assembly State",
        description="Record the assembled transform automatically for parts that do not have one yet",
        default=True,
    )

    # ----------------------------------------------------------------- camera
    use_camera: BoolProperty(
        name="Animate Camera",
        description="Build and animate a camera rig together with the parts",
        default=False,
    )
    camera_object: PointerProperty(name="Camera", type=Object)
    camera_pivot: PointerProperty(name="Camera Pivot", type=Object)
    camera_target: PointerProperty(name="Camera Target", type=Object)

    camera_mode: EnumProperty(
        name="Camera Mode",
        description="How the camera move is defined",
        items=[
            ('ORBIT', "Orbit", "Automatic circular orbit that frames the whole exploded assembly"),
            ('SUBJECT', "Frame Object", "Pick one object, usually the PCB, and let the camera work out a "
                                        "good distance from its size and orbit around it"),
            ('POSES', "From Viewport", "Frame the shot in the viewport and capture it as the start and "
                                       "end pose of the camera move"),
        ],
        default='ORBIT',
    )

    camera_subject: PointerProperty(
        name="Subject",
        description="Object the camera frames and orbits around. Its size decides the camera distance",
        type=Object,
        poll=_subject_poll,
    )

    # Poses captured from the viewport, stored as world matrices.
    camera_pose_start: FloatVectorProperty(
        name="Start Pose", size=16, default=IDENTITY_16,
        description="Captured camera matrix for the first frame",
    )
    camera_pose_end: FloatVectorProperty(
        name="End Pose", size=16, default=IDENTITY_16,
        description="Captured camera matrix for the last frame",
    )
    camera_pose_start_set: BoolProperty(name="Start Pose Captured", default=False)
    camera_pose_end_set: BoolProperty(name="End Pose Captured", default=False)
    camera_pose_start_lens: FloatProperty(name="Start Focal Length", default=50.0, min=1.0)
    camera_pose_end_lens: FloatProperty(name="End Focal Length", default=50.0, min=1.0)
    camera_animate_focal: BoolProperty(
        name="Animate Focal Length",
        description="Blend the focal length between the two captured views as well as the position",
        default=True,
    )

    camera_focal: FloatProperty(
        name="Focal Length",
        description="Camera focal length in millimeters",
        default=50.0,
        min=1.0,
        soft_max=300.0,
    )
    camera_auto_distance: BoolProperty(
        name="Auto Frame",
        description="Compute the camera distance so the exploded assembly fits in frame",
        default=True,
    )
    camera_distance: FloatProperty(
        name="Distance",
        description="Manual camera distance from the assembly center",
        default=6.0,
        min=0.001,
        unit='LENGTH',
    )
    camera_margin: FloatProperty(
        name="Framing Margin",
        description="Extra room around the assembly when auto framing",
        default=1.25,
        min=1.0,
        soft_max=3.0,
    )
    camera_height: FloatProperty(
        name="Height",
        description="Camera height above the assembly center, as a factor of the assembly radius",
        default=0.55,
        soft_min=-3.0,
        soft_max=3.0,
    )
    camera_start_angle: FloatProperty(
        name="Start Angle",
        description="Orbit angle at the first frame",
        default=-0.523599,
        subtype='ANGLE',
    )
    camera_orbit: FloatProperty(
        name="Orbit",
        description="How far the camera travels around the assembly during the animation",
        default=2.0943951,
        subtype='ANGLE',
    )
    camera_use_dolly: BoolProperty(
        name="Dolly",
        description="Push the camera in or pull it out during the animation",
        default=True,
    )
    camera_zoom_start: FloatProperty(
        name="Distance Start",
        description="Distance multiplier at the first frame",
        default=1.35,
        min=0.05,
        soft_max=4.0,
    )
    camera_zoom_end: FloatProperty(
        name="Distance End",
        description="Distance multiplier at the last frame",
        default=1.0,
        min=0.05,
        soft_max=4.0,
    )
    camera_height_end: FloatProperty(
        name="Height End",
        description="Height factor at the last frame",
        default=0.35,
        soft_min=-3.0,
        soft_max=3.0,
    )
    camera_interpolation: EnumProperty(
        name="Interpolation",
        description="Interpolation of the camera keyframes",
        items=INTERPOLATION_ITEMS,
        default='SINE',
    )
    camera_easing: EnumProperty(
        name="Easing",
        description="Easing of the camera keyframes",
        items=EASING_ITEMS,
        default='EASE_IN_OUT',
    )
    camera_set_active: BoolProperty(
        name="Make Scene Camera",
        description="Set the generated camera as the active scene camera",
        default=True,
    )
    camera_mirror_on_assemble: BoolProperty(
        name="Mirror Camera On Assemble",
        description="Play the camera move backwards when building an Assemble animation, so it "
                    "continues where an Explode pass ended. Leave this off and the start framing is "
                    "always the first frame, whichever animation you build",
        default=False,
    )

    # ------------------------------------------------------------------- misc
    last_report: StringProperty(name="Last Report", default="")


CLASSES = (
    EAS_ObjectProperties,
    EAS_SceneProperties,
)


def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    Scene.eas = PointerProperty(type=EAS_SceneProperties)
    Object.eas = PointerProperty(type=EAS_ObjectProperties)


def unregister():
    del Object.eas
    del Scene.eas
    for cls in reversed(CLASSES):
        bpy.utils.unregister_class(cls)
